config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Hairillusion::Application.routes.draw do 

  root 'home#index'

  mount Sidekiq::Web => '/sidekiq'
  
  get '/distributors/subregion_options' => 'distributors#subregion_options' 
  get '/set_setting_carriers' => 'distributors#set_setting_carriers' 
  
  post '/add_cart' => 'home#add_cart'
  get '/patent' => 'home#patent'
  get '/get_discount'=> 'home#get_discount'
  get '/update_color'=> 'home#update_color'
  post '/create_order' => 'home#create_order'
  post '/create_club_order' => 'home#create_club_order'
  post '/post_enquiry' => 'home#post_enquiry' 
  
  post '/subscribe' => "home#subscribe"
  get '/payment' => 'home#payment'   
  
  post '/get_shipping_carreirs' =>'home#get_shipping_carreirs'
  get '/get_shipping_states' =>'home#get_shipping_states'
  get '/set_shipping_values' => 'home#set_shipping_values'
    
  get '/edit_card' => 'home#edit_card'   
  post '/update_card' => 'home#update_card'
  get '/videos'=>'home#videos'
  
  get '/apply_in_sixty_seconds' => 'home#apply_in_sixty_seconds'   
  
  post '/create_customer' => 'home#create_customer' 
  post '/process_login' => 'home#process_login'
  
  get '/edit_color' => 'home#edit_color'
  post '/update_color' => 'home#update_color'
  
  
  get '/auto_ship' => 'home#auto_ship'
  get '/account_details' => 'home#account_details'
  get '/past_orders' => 'home#past_orders'
  get '/sign_out' => 'home#sign_out'
  get '/login' => 'home#login'
  get 'dashboard' => 'home#dashboard'
  get '/message_thanks' => 'home#message_thanks' 
  #get '/club_details' => 'home#club_details'
  get '/cart' => 'home#cart'
  get '/checkout' => "home#checkout"
  get '/faq' => 'home#faq'
  get '/thankyou' => 'home#thanks'
  
  get '/edit_address'=> 'home#edit_address'
  post '/update_address'=> 'home#update_address'
  
  get '/product_details' => 'home#product_details'
  get '/remove_product_from_cart' => 'home#remove_product_from_cart'
  get '/get_billing_states' => "home#get_billing_states"
  
  get '/products' => 'home#products'
  post '/order_confirmation' => 'home#after_payment'
  
  post '/confirmation' => 'home#after_payment'
    
  post '/save_forum' => 'home#save_forum' 
  post '/thankyou' => 'home#thankyou'
  get '/buy_now' =>"home#buy_now"
  get '/get_total_price' => 'distributors#get_total_price'
   
  post '/get_forums' => 'home#get_forums' 
  get '/new_forum' => 'home#new_forum' 
  get '/get_states' => 'home#get_states'
  get '/add_to_cart' => 'home#add_to_cart'
  get '/remove_from_cart' => 'home#remove_from_cart'
  get '/fibre_hold' => 'home#fibre_hold'
  
  get '/mirror' => 'home#mirror'
  get '/optimizer' => 'home#optimizer'
  
  get '/forum' => 'home#forum'
  get '/more_reviews' => 'home#more_reviews'  
  
  get '/terms' => 'home#terms'
  get '/testimonials' => 'home#testimonials'
  get '/photos' => 'home#photos'
  get '/how_it_works' => 'home#how_it_works'
  get '/what_is_it' => 'home#what_is_it'
  get '/about_us' => 'home#about_us'
  get '/contact_us' => 'home#contact_us'
  get '/color' => 'home#color'
  get '/mens_hair_loss' => 'home#mens_hair_loss'
  get '/womens_hair_loss' => 'home#womens_hair_loss'

  get '/forgot_password' => 'home#forgot_password'
  post '/forgot_password_email' => 'home#forgot_password_email'
  get '/password_reset_success' => 'home#password_reset_success'
  
  resources :orders, only: [:new, :create, :buy_product] do
    collection do
      get :confirmation
      get :buy_product 
    end
  end
   
  

  resources :distributors, only: [:new, :create] do
    collection do
      get :confirmation
      get :show
      get :edit
      put :update
      post :login
      get :logout
      post :order
      get :past_orders
    end
  end

  resources :health_check, only: [:index]

  namespace :admin do
    get "/" => "orders#index"

    resources :customers, only: [:index, :show, :edit, :update] do
      resources :orders, only: [:index, :new, :create]
    end
     
    resources :forums do
    end 
    
    resources :domain_distributors do
      collection do
        post :filter_report 
        get :download_report 
      end 
    end
    
    resources :distributors, except: [:destroy] do
      resources :orders, only: [:index, :new, :create]

      member do
        get :approve
      end
    end

    resources :orders, except: [:destroy]  do
      member do
        put :refund 
      end
      collection do
        get :pull_details_from_shopify 
        get :distributor_orders
      end
    end

    resources :shipments, except: [:destroy]
  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  extend GridTable

  has_many :orders, as: :orderer, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
  validates :address1, presence: true
  validates :city, presence: true
  validates :country, presence: true
  validates :state, presence: true
#  validates :zip, presence: true#, numericality: true, format: { with: %r{\d{5}(-\d{4})?}, message: "should be 12345 or 12345-1234" }

  grid_table_control :created_at
  grid_table_control :first_name
  grid_table_control :last_name
  grid_table_control :email
  grid_table_control :city
  grid_table_control :state

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::ApplicationController
  respond_to :html
  respond_to :js, only: [:index]

  def index
    respond_to do |format|
      format.html {}
      format.js do
        @customers = Customer.all

        grid_table_for(@customers, index_params)
      end
    end
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  private
  def index_params
    params.permit [].concat(Customer.grid_table_strong_params)
  end
end

app/views/admin/customers/_row.html.erb
<tr>
  <td><%= customer.created_at %></td>
  <td><%= customer.first_name %></td>
  <td><%= customer.last_name %></td>
  <td><%= mail_to(customer.email) %></td>
  <td><%= customer.city %></td>
  <td><%= customer.state %></td>
  
  <td>
    <%= link_to icon_text('Info', 'glyphicon glyphicon-info-sign'), admin_customer_path(customer), class: 'btn btn-sm btn-success' %>
    <%= link_to icon_text('Edit', 'glyphicon glyphicon-pencil'), edit_admin_customer_path(customer), class: 'btn btn-sm btn-primary' %>
  </td>
</tr>

app/views/admin/customers/index.html.erb
<table class="table table-striped table-bordered table-hover table-condensed grid-table" data-url="<%= admin_customers_path %>">
  <thead>
    <tr>
      <th data-field="created_at" data-sort="true" data-default-sort="asc">Created</th>
      <th data-field="first_name" data-sort="true">First Name</th>
      <th data-field="last_name" data-sort="true">Last Name</th>
      <th data-field="email" data-sort="true">Email</th>
      <th data-field="city" data-sort="true">City</th>
      <th data-field="state" data-sort="true">State/Region/Province</th>
      <th></th>
    </tr>
    <tr class="filters">
      <th class="filter">
        <%= text_field_tag :filter_created_at, nil, 'data-field' => 'created_at', class: 'row-filter' %>
      </th>
      <th class="filter">
        <%= text_field_tag :filter_first_name, nil, 'data-field' => 'first_name', class: 'row-filter', size: 10 %>
      </th>
      <th class="filter">
        <%= text_field_tag :filter_last_name, nil, 'data-field' => 'last_name', class: 'row-filter', size: 10 %>
      </th>
      <th class="filter">
        <%= text_field_tag :filter_email, nil, 'data-field' => 'email', class: 'row-filter' %>
      </th>
      <th class="filter">
        <%= text_field_tag :filter_city, nil, 'data-field' => 'city', class: 'row-filter', size: 10 %>
      </th>
      <th class="filter">
        <%= text_field_tag :filter_state, nil, 'data-field' => 'state', class: 'row-filter', size: 4 %>
      </th>
      <th></th>
    </tr>
  </thead>
  <tbody></tbody>
  <tfoot>
    <tr>
      <th colspan="7">
        <%= render 'admin/shared/grid_pager' %>
      </th>
    </tr>
  </tfoot>
</table>

app/views/admin/customers/show.html.erb
<div class="row">
  <div class="col-md-6 well">
    <p>
      <strong>First Name:</strong>
      <%= @customer.first_name %>
    <p>

    <p>
      <strong>Last Name:</strong>
      <%= @customer.last_name %>
    <p>

    <p>
      <strong>Email:</strong>
      <%= @customer.email %>
    <p>

    <p>
      <strong>Address:</strong>
      <br/>
      <%= @customer.address1 %><br/>
      <% if @customer.address2.present? %>
        <%= @customer.address2 %><br/>
      <% end %>
      <%= "#{@customer.city}, #{@customer.state} #{@customer.zip} #{get_country_name(@customer.country, false)}" %>
    <p>

    <p>
      <%= link_to icon_text('Edit', 'glyphicon glyphicon-pencil'), edit_admin_customer_path(@customer), class: 'btn btn-sm btn-primary' %>
      <%= link_to icon_text('Past Orders', 'glyphicon glyphicon-time'), admin_customer_orders_path(@customer), class: 'btn btn-sm btn-primary' %>
      <%= link_to icon_text('New Order', 'glyphicon glyphicon-credit-card'), new_admin_customer_order_path(@customer), class: 'btn btn-sm btn-success' %>
    </p>
  </div>
</div>