config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Hairillusion::Application.routes.draw do 

  root 'home#index'

  mount Sidekiq::Web => '/sidekiq'
  
  get '/distributors/subregion_options' => 'distributors#subregion_options' 
  get '/set_setting_carriers' => 'distributors#set_setting_carriers' 
  
  post '/add_cart' => 'home#add_cart'
  get '/patent' => 'home#patent'
  get '/get_discount'=> 'home#get_discount'
  get '/update_color'=> 'home#update_color'
  post '/create_order' => 'home#create_order'
  post '/create_club_order' => 'home#create_club_order'
  post '/post_enquiry' => 'home#post_enquiry' 
  
  post '/subscribe' => "home#subscribe"
  get '/payment' => 'home#payment'   
  
  post '/get_shipping_carreirs' =>'home#get_shipping_carreirs'
  get '/get_shipping_states' =>'home#get_shipping_states'
  get '/set_shipping_values' => 'home#set_shipping_values'
    
  get '/edit_card' => 'home#edit_card'   
  post '/update_card' => 'home#update_card'
  get '/videos'=>'home#videos'
  
  get '/apply_in_sixty_seconds' => 'home#apply_in_sixty_seconds'   
  
  post '/create_customer' => 'home#create_customer' 
  post '/process_login' => 'home#process_login'
  
  get '/edit_color' => 'home#edit_color'
  post '/update_color' => 'home#update_color'
  
  
  get '/auto_ship' => 'home#auto_ship'
  get '/account_details' => 'home#account_details'
  get '/past_orders' => 'home#past_orders'
  get '/sign_out' => 'home#sign_out'
  get '/login' => 'home#login'
  get 'dashboard' => 'home#dashboard'
  get '/message_thanks' => 'home#message_thanks' 
  #get '/club_details' => 'home#club_details'
  get '/cart' => 'home#cart'
  get '/checkout' => "home#checkout"
  get '/faq' => 'home#faq'
  get '/thankyou' => 'home#thanks'
  
  get '/edit_address'=> 'home#edit_address'
  post '/update_address'=> 'home#update_address'
  
  get '/product_details' => 'home#product_details'
  get '/remove_product_from_cart' => 'home#remove_product_from_cart'
  get '/get_billing_states' => "home#get_billing_states"
  
  get '/products' => 'home#products'
  post '/order_confirmation' => 'home#after_payment'
  
  post '/confirmation' => 'home#after_payment'
    
  post '/save_forum' => 'home#save_forum' 
  post '/thankyou' => 'home#thankyou'
  get '/buy_now' =>"home#buy_now"
  get '/get_total_price' => 'distributors#get_total_price'
   
  post '/get_forums' => 'home#get_forums' 
  get '/new_forum' => 'home#new_forum' 
  get '/get_states' => 'home#get_states'
  get '/add_to_cart' => 'home#add_to_cart'
  get '/remove_from_cart' => 'home#remove_from_cart'
  get '/fibre_hold' => 'home#fibre_hold'
  
  get '/mirror' => 'home#mirror'
  get '/optimizer' => 'home#optimizer'
  
  get '/forum' => 'home#forum'
  get '/more_reviews' => 'home#more_reviews'  
  
  get '/terms' => 'home#terms'
  get '/testimonials' => 'home#testimonials'
  get '/photos' => 'home#photos'
  get '/how_it_works' => 'home#how_it_works'
  get '/what_is_it' => 'home#what_is_it'
  get '/about_us' => 'home#about_us'
  get '/contact_us' => 'home#contact_us'
  get '/color' => 'home#color'
  get '/mens_hair_loss' => 'home#mens_hair_loss'
  get '/womens_hair_loss' => 'home#womens_hair_loss'

  get '/forgot_password' => 'home#forgot_password'
  post '/forgot_password_email' => 'home#forgot_password_email'
  get '/password_reset_success' => 'home#password_reset_success'
  
  resources :orders, only: [:new, :create, :buy_product] do
    collection do
      get :confirmation
      get :buy_product 
    end
  end
   
  

  resources :distributors, only: [:new, :create] do
    collection do
      get :confirmation
      get :show
      get :edit
      put :update
      post :login
      get :logout
      post :order
      get :past_orders
    end
  end

  resources :health_check, only: [:index]

  namespace :admin do
    get "/" => "orders#index"

    resources :customers, only: [:index, :show, :edit, :update] do
      resources :orders, only: [:index, :new, :create]
    end
     
    resources :forums do
    end 
    
    resources :domain_distributors do
      collection do
        post :filter_report 
        get :download_report 
      end 
    end
    
    resources :distributors, except: [:destroy] do
      resources :orders, only: [:index, :new, :create]

      member do
        get :approve
      end
    end

    resources :orders, except: [:destroy]  do
      member do
        put :refund 
      end
      collection do
        get :pull_details_from_shopify 
        get :distributor_orders
      end
    end

    resources :shipments, except: [:destroy]
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::ApplicationController
  respond_to :html, except: [:shipping]
  respond_to :js, only: [:index]
  
  def distributor_orders
    distributor_ids = Distributor.all.collect(&:id)
 
    @orders = Order.where("orderer_id in (?) and orderer_type='Distributor'",distributor_ids).order("DATE(created_at) DESC").page(params[:page]).per_page(10) 
  end
  
  def index
    if params[:customer_id]
      @orderer = Customer.find(params[:customer_id])
    elsif params[:distributor_id]
      @orderer = Distributor.find(params[:distributor_id])
    end

    respond_to do |format|
      format.html {}
      format.js do
        if @orderer.present?
          @orders = @orderer.orders
        else
          @orders = Order.includes(:orderer)
        end

        grid_table_for(@orders, index_params)
      end
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    if params[:distributor_id]
      @distributor = Distributor.find(params[:distributor_id])
      @order = @distributor.orders.build
      @credit_card = CreditCard.new

      Product.all.each do |p|
        @order.order_items<< OrderItem.new(product: p, quantity: 0)
      end
    elsif params[:customer_id]
      @customer = Customer.find(params[:customer_id])
      @order = @customer.orders.build
      @order_item = @order.order_items.build
      @credit_card = CreditCard.new
    else
      @customer = Customer.new
      @order = @customer.orders.build
      @order_item = @order.order_items.build
      @credit_card = CreditCard.new
    end
  end

  def create
    if params[:distributor_id].present?
      @orderer = Distributor.find(params[:distributor_id])
      orderer_valid = true
    elsif params[:customer_id].present?
      @orderer = Customer.find(params[:customer_id])
      orderer_valid = true
    else
      @orderer = Customer.new(customer_params)
      orderer_valid = @orderer.valid?
    end

    @order = @orderer.orders.build(order_params)
    @order.host = request.host
    @credit_card = CreditCard.new(cc_params)

    order_valid = @order.valid?
    credit_card_valid = @credit_card.valid?

    if orderer_valid && order_valid && credit_card_valid
      begin
        if @orderer.stripe_id.blank?
          stripe_customer = Stripe::Customer.create(
            email: @orderer.email
          )

          @orderer.stripe_id = stripe_customer.id
        end

        total_price = @order.total(@orderer.try(:price))

        charge = Stripe::Charge.create(
          amount: total_price,
          description: @order.description,
          currency: 'usd',
          card: cc_params
        )

        @order.stripe_id = charge.id 
        @orderer.save!
        @order.save! 
        OrderMailer.receipt(@order, total_price).deliver

        flash[:notice] = "Thanks for your order"
        redirect_to params[:distributor_id].present? ? admin_distributor_path(@orderer) : admin_customer_path(@orderer)
      rescue Stripe::CardError => e
        # Since it's a decline, Stripe::CardError will be caught
        body = e.json_body
        err  = body[:error]

        puts "Status is: #{e.http_status}"
        puts "Type is: #{err[:type]}"
        puts "Code is: #{err[:code]}"
        # param is '' in this case
        puts "Param is: #{err[:param]}"
        puts "Message is: #{err[:message]}"

        flash[:alert] = err[:message]

        render admin_order_path(@order)
      rescue => e
        # Something else happened, completely unrelated to Stripe
        flash[:alert] = e.message
        render admin_order_path(@order)
      end
    else
      render admin_order_path(@order)
    end
  end

  def edit
    @order = Order.find(params[:id])
    if @order.orderer_type == Distributor.name
      @distributor = @order.orderer
    elsif @order.orderer_type == Customer.name
      @customer = @order.orderer
      @order_item = @order.order_items.build
    end

    @credit_card = CreditCard.new
  end

  def update
    @order = Order.find(params[:id])

    if @order.update_attributes(order_params)
      redirect_to admin_order_path(@order)
    else
      render :edit
    end
  end

  def refund
    @order = Order.find(params[:id])

    begin
      @order.stripe_charge.refund
      @order.update_attribute(:refunded_at, Time.now)

      redirect_to(admin_order_path(@order))
    rescue => e
      # Something else happened, completely unrelated to Stripe
      flash[:alert] = e.message
      render admin_order_path(@order)
    end
  end
  
  def pull_details_from_shopify
    shop_url = "https://a98b179d72117d149e44ae83796e4c64:b62b5da657f75898e1d45eb6a6e0e247@hair-illusion-llc.myshopify.com/admin"
    ShopifyAPI::Base.site = shop_url 
    
    customers = ShopifyAPI::Customer.all  
    i = 0
    customers.each do |c|  
      email = c.email
      db_customer = Customer.find_by_email(email) 
       
      if db_customer.nil?
        address = c.default_address
        i = i+1
        customer = Customer.new(:email=>email, :first_name=>c.first_name, :last_name=>c.last_name, :address1 => address.address1,:address2 => address.address2, :created_at=>c.created_at,
        :city=> address.city, :country =>address.country_code, :state=>address.province, :zip=>address.zip, :stripe_id=>"shopify"+Time.now.to_i.to_s+i.to_s, :shopify_customer_id=>c.id)
        customer.save(validate: false)    
      else 
        db_customer.shopify_customer_id = c.id
        db_customer.save(validate: false)
      end
    end
    
    orders = ShopifyAPI::Order.all 
    orders.each do |o|   
      order = Order.find_by_shopify_order_id(o.id)
      if order.nil? 
        customer = Customer.find_by_shopify_customer_id(o.customer.id) 
        customer_id = customer.id 
        
        order = Order.new(:orderer_id=>customer_id, :orderer_type=>'Customer', :shopify_order_id=>o.id, :created_at=>o.processed_at)
        order.save
        
        host = ""
        landing_site = o.landing_site
         
        if landing_site.include?('hairillusion.net')
          host = "hairillusion.net" 
          distributor = DomainDistributor.where(:domain=>"hairillusion.net").first
          if distributor
            distributor_order = DistributorOrder.new(:distributor_id=>distributor.id, :order_id=>order.id, :created_at=>order.created_at)
            distributor_order.save
          end
        elsif landing_site.include?('buyhairillusion.com') 
          host = "buyhairillusion.com" 
          distributor = DomainDistributor.where(:domain=>"buyhairillusion.com").first
          if distributor
            distributor_order = DistributorOrder.new(:distributor_id=>distributor.id, :order_id=>order.id, :created_at=>order.created_at)
            distributor_order.save
          end
        elsif landing_site.include?('gethairillusion.com') 
          host = 'gethairillusion.com'
          distributor = DomainDistributor.where(:domain=>"gethairillusion.com").first
          if distributor
            distributor_order = DistributorOrder.new(:distributor_id=>distributor.id, :order_id=>order.id, :created_at=>order.created_at)
            distributor_order.save
          end 
        elsif landing_site.include?('hairillusion.com') 
          host = 'hairillusion.com'
          distributor = DomainDistributor.where(:domain=>"hairillusion.com").first
          if distributor
            distributor_order = DistributorOrder.new(:distributor_id=>distributor.id, :order_id=>order.id, :created_at=>order.created_at)
            distributor_order.save
          end 
        else  
          DomainDistributor.all.each do |d| 
            if landing_site.include?(d.domain)  
              distributor_order = DistributorOrder.new(:distributor_id=>d.id, :order_id=>order.id, :created_at=>order.created_at)
              distributor_order.save
              host = "#{d.domain}"  
              OrderMailer.send_order_email(distributor_order.distributor_id, distributor_order.order_id).deliver
            end 
          end
        end  
        
        order.update_attribute(:host,host) 
        o.line_items.each do |item| 
          product = Product.where("lower(description) = ?", item.variant_title.downcase).first  
          product_id = nil 
          product_id = product.id unless product.nil?   
          price = item.price.to_f*100 
          order_item = OrderItem.new(:quantity=>item.quantity, :price=>price, :order_id=>order.id,:product_id=>product_id )  
          order_item.save!   
        end 
      end
    end
  end

  private
  def index_params
    params.permit [].concat(Order.grid_table_strong_params)
  end

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :email, :address1, :address2, :city, :state, :zip, :country)
  end

  def order_params
    params.require(:order).permit(:orderer_id, order_items_attributes: [:product_id, :quantity])
  end

  def cc_params
    params.require(:credit_card).permit(:name, :number, :cvc, :exp_month, :exp_year)
  end
end

app/views/admin/orders/_customer_form.html.erb
<div id="checkoutForm" class="row">
  <div class="col-md-6">
    <h2>Order Form</h2>

    <%= form_for @order, url: @customer.new_record? ? admin_orders_path : admin_customer_orders_path(@customer), html: { class: 'form-horizontal' } do |f| %>
      <%= f.fields_for :order_items, @order_item do |oi| %>
        <%= control_group(@order_item, :color, label: 'Select Color') do %>
		<%= oi.select( "product_id", options_from_collection_for_select(Product.all, "id", "description", @order.order_items[0].product_id), {:include_blank => false}, { :class=>"form-control required"})%>  
        <% end %>

        <%= control_group(@order_item, :color, label: 'Quantity') do %>
          <%= oi.number_field :quantity, min: 1, step: 1, class: 'form-control required order-quantity', data: { price: 59.95 } %></td>
        <% end %>
      <% end %>

      <div class="contact_info">
        <h4>PERSONAL INFORMATION</h4>
        <%= fields_for @customer do |c| %>
          <%= control_group(@customer, :first_name, label: 'First Name') do %>
            <%= c.text_field :first_name, class: 'form-control required' %>
          <% end %>

          <%= control_group(@customer, :last_name, label: 'Last Name') do %>
            <%= c.text_field :last_name, class: 'form-control required' %>
          <% end %>

          <%= control_group(@customer, :email, label: 'Email') do %>
            <%= c.email_field :email, class: 'form-control required' %>
          <% end %>

          <%= control_group(@customer, :address1, label: 'Street Address') do %>
            <%= c.text_field :address1, class: 'form-control required' %>
          <% end %>

          <%= control_group(@customer, :address2, label: 'Suite / Apt') do %>
            <%= c.text_field :address2, class: 'form-control' %>
          <% end %>

          <%= control_group(@customer, :city, label: 'City') do %>
            <%= c.text_field :city, class: 'form-control required' %>
          <% end %>
			
		  <%= control_group(@customer, :country, label: 'Country') do %>
            <%= c.country_select :country, { prompt: 'Please select a country'}, { class: 'form-control required' } %>
          <% end %> 
          
          <%= control_group(@customer, :state, label: 'State/Region/Province') do %>
            <%= c.text_field :state,  class: 'form-control required' %>
          <% end %>

          <%= control_group(@customer, :zip, label: 'Postal/Zip Code') do %>
            <%= c.text_field :zip, class: 'form-control required'%>
          <% end %>
        <% end %>

      </div>
      <div class="payment">
        <h4>CREDIT CARD INFORMATION</h4>
        <%= fields_for @credit_card do |cc| %>
          <%= control_group(@credit_card, :name, label: 'Name on Card') do %>
            <%= cc.text_field :name, class: 'form-control required', autocomplete: :off %>
          <% end %>

          <%= control_group(@credit_card, :number, label: 'Card Number') do %>
            <%= cc.number_field :number, class: 'form-control required', autocomplete: :off, :size => 20 %>
          <% end %>

          <%= control_group(@credit_card, :cvc, label: 'CVC') do %>
            <%= cc.number_field :cvc, class: 'form-control required', autocomplete: :off, :size => 4 %>
          <% end %>

          <%= control_group(@credit_card, :exp_month, label: 'Expiration') do %>
            <div class="row">
              <div class="col-md-4">
                <%= select_month(nil, { :prefix => :credit_card, :field_name => :exp_month, use_month_numbers: true, prompt: 'MM' }, { class: 'form-control required' }) %>
              </div>
              <div class="col-md-8">
                <%= select_year(nil, { :prefix => :credit_card, :field_name => :exp_year, start_year: Time.now.year, end_year: Time.now.year + 10, prompt: 'YYYY' }, { class: 'form-control required' }) %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>

      <div class="form-group">
        <div style="text-align:center;" class="col-md-12">
          <%= f.submit 'Create Order', class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/orders/_distributor_form.html.erb
<div id="checkoutForm" class="row">
  <div class="col-md-6">
    <h2>Order Form</h2>

    <%= form_for @order, url: admin_distributor_orders_path(@distributor), html: { class: 'form-horizontal' } do |f| %>
      <%= f.hidden_field :orderer_id %>
      <table class="table table-bordered table-condensed">
        <thead>
          <th>Product</th>
          <th>Quantity</th>
        </thead>
        <tbdoy>
          <%= f.fields_for :order_items do |oi| %>
            <tr>
              <td>
                <%= oi.object.product.description %>
                <%= oi.hidden_field :product_id %>
              </td>
              <td><%= oi.number_field :quantity, min: 0, step: 1, class: 'form-control required order-quantity', data: { price: @distributor.price / 100.0 } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <div class="payment">
        <h4>CREDIT CARD INFORMATION</h4>
        <%= fields_for @credit_card do |cc| %>
          <%= control_group(@credit_card, :name, label: 'Name on Card') do %>
            <%= cc.text_field :name, class: 'form-control required', autocomplete: :off %>
          <% end %>

          <%= control_group(@credit_card, :number, label: 'Card Number') do %>
            <%= cc.number_field :number, class: 'form-control required', autocomplete: :off, :size => 20 %>
          <% end %>

          <%= control_group(@credit_card, :cvc, label: 'CVC') do %>
            <%= cc.number_field :cvc, class: 'form-control required', autocomplete: :off, :size => 4 %>
          <% end %>

          <%= control_group(@credit_card, :exp_month, label: 'Expiration') do %>
            <div class="row">
              <div class="col-md-4">
                <%= select_month(nil, { :prefix => :credit_card, :field_name => :exp_month, use_month_numbers: true, prompt: 'MM' }, { class: 'form-control required' }) %>
              </div>
              <div class="col-md-8">
                <%= select_year(nil, { :prefix => :credit_card, :field_name => :exp_year, start_year: Time.now.year, end_year: Time.now.year + 10, prompt: 'YYYY' }, { class: 'form-control required' }) %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>

      <div class="form-group">
        <div style="text-align:center;" class="col-md-12">
          <p>Your Total Today is <strong>$<span id="order-total-price"><%= number_to_currency(@order.total / 100.0) %></span></strong></p>
        </div>
      </div>
      <div class="form-group">
        <div style="text-align:center;" class="col-md-12">
          <%= f.submit 'Create Order', class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>

app/views/admin/orders/_row.html.erb
<tr>
  <td><%= order.created_at %></td>
  <td><%= order.id %></td>
  <td>
    <% if order.orderer_type == Customer.name %>
      <%= link_to("#{order.orderer.first_name} #{order.orderer.last_name}", admin_customer_path(order.orderer)) %>
    <% elsif order.orderer_type == Distributor.name %>
      <%= link_to(order.orderer.company_name, admin_distributor_path(order.orderer)) %>
    <% end %>
  </td>
  <td><%= order.host %></td>
  <td>
    <% if order.shipment.present? %>
      <%= link_to(order.shipment.created_at, admin_shipment_path(order.shipment)) %>
    <% end %>
  </td>
  <td>
    <%= link_to icon_text('Detail', 'glyphicon glyphicon-info-sign'), admin_order_path(order), class: 'btn btn-sm btn-success' %>
    <%= link_to icon_text('Edit', 'glyphicon glyphicon-pencil'), edit_admin_order_path(order), class: 'btn btn-sm btn-primary' %>
  </td>
</tr>

app/views/admin/orders/distributor_orders.html.erb
 
<%= will_paginate @orders, :container => false %>

<br />
<table class="table table-striped table-bordered table-hover table-condensed grid-table">
	<tr>
		<th>Date</th> 
		<th>Distributor</th>
		<th>Details</th>
	</tr>
	<% @orders.each do |order| %>
		<tr>
			<td>
				<%= order.created_at.strftime("%d/%m/%Y at %H:%M") %>
			</td>
			<td> 
				<%= link_to("#{order.try(:orderer).try(:name)}", admin_distributor_path(order.try(:orderer))) %>
 
			</td>
			<td>  
				<%= link_to("Order Details", admin_distributor_orders_path(order.try(:orderer))) %> 
			</td>
		</tr>
	<%end%>
</table> 

<%= will_paginate @orders, :container => false %>

app/views/admin/orders/edit.html.erb
<% if @order.orderer_type == Distributor.name %>
  <%= render 'distributor_form' %>
<% elsif @order.orderer_type == Customer.name %>
  <%= render 'customer_form' %>
<% end %>

app/views/admin/orders/index.html.erb
<% if @orderer.present? %>
  <% if @orderer.class == Distributor %>
    <% url = admin_distributor_orders_path(@orderer) %>
    <h2><%= @orderer.company_name %> (Distributor) Orderes</h2>
  <% elsif @orderer.class == Customer %>
    <% url = admin_customer_orders_path(@orderer) %>
    <h2><%= @orderer.name %> (Customer) Orders</h2>
  <% else %>
    <% url = admin_orders %>
  <% end %>
<% end %>

<table class="table table-striped table-bordered table-hover table-condensed grid-table" data-url="<%= url %>">
  <thead>
    <tr>
      <th data-field="created_at" data-sort="true" data-default-sort="desc">Created</th>
      <th data-field="id" data-sort="true">Order #</th>
      <th data-field="orderer" data-sort="true">Ordered By</th>
      <th data-field="host" data-sort="true">Host</th>
      <th>Shipped</th>
      <th></th>
    </tr>
    <tr class="filters">
      <th class="filter">
        <%= text_field_tag :filter_created_at, nil, 'data-field' => 'created_at' %>
      </th>
      <th class="filter">
        <%= text_field_tag :filter_id, nil, 'data-field' => 'id' %>
      </th>
      <th class="filter">
        <%= text_field_tag :filter_orderer, nil, 'data-field' => 'orderer' %>
      </th>
      <th class="filter">
        <%= text_field_tag :filter_host, nil, 'data-field' => 'host' %>
      </th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody></tbody>
  <tfoot>
    <tr>
      <th colspan="6">
        <%= render 'admin/shared/grid_pager' %>
      </th>
    </tr>
  </tfoot>
</table>

app/views/admin/orders/new.html.erb
<% if @distributor.present? %>
  <%= render 'distributor_form' %>
<% else %>
  <%= render 'customer_form' %>
<% end %>

app/views/admin/orders/pull_details_from_shopify.js.erb
window.location.reload();

app/views/admin/orders/show.html.erb
<div class="row">
  <div class="col-md-6 well">
    <p>
      <strong>Order #:</strong>
      <%= @order.id %>
    <p>

    <p>
      <strong>Ordered By:</strong>
      <% if @order.orderer_type == Customer.name %>
        <%= link_to("#{@order.orderer.first_name} #{@order.orderer.last_name} (Customer)", admin_customer_path(@order.orderer)) %>
      <% elsif @order.orderer_type == Distributor.name %>
        <%= link_to("#{@order.orderer.company_name} (Distributor)", admin_distributor_path(@order.orderer)) %>
      <% end %>
    <p>

    <p>
      <strong>Ordered At:</strong>
      <%= @order.created_at %>
    <p>

    <% if @order.shipment.present? %>
      <p>
        <strong>Shipped At:</strong>
        <%= link_to(@order.shipment.created_at, admin_shipment_path(@order.shipment)) %>
      </p>
    <% end %>

    <p>
      <% if @order.refunded_at %>
        <strong>Refunded At:</strong>
        <%= @order.refunded_at %>
      <% else %>
        <%= link_to('Refund Order', refund_admin_order_path(@order), method: :put, class: 'btn btn-sm btn-success') %>
      <% end %>
    <p>

    <p>
      <table class="table table-striped table-bordered table-hover table-condensed">
        <thead>
          <th>Product</th>
          <th>Product Code</th>
          <th>Quantity</th>
          <th>Price</th>
          <th>Total</th>
        </thead>
        <tbdoy>
          <% @order.order_items.each do |order_item| %>
            <tr>
              <td><%= order_item.product.description %></td>
              <td><%= order_item.product.product_code %></td>
              <td><%= order_item.quantity %></td>
              <td><%= number_to_currency(order_item.price / 100.0) %></td>
              <td><%= number_to_currency(order_item.total / 100.0) %></td>
            </tr>
          <% end %>
        </tbdoy>
      </table>
    </p>

    <p>
      <%= link_to icon_text('Edit', 'glyphicon glyphicon-pencil'), edit_admin_order_path(@order), class: 'btn btn-sm btn-primary' %>
    </p>
  </div>
</div>