config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Hairillusion::Application.routes.draw do 

  root 'home#index'

  mount Sidekiq::Web => '/sidekiq'
  
  get '/distributors/subregion_options' => 'distributors#subregion_options' 
  get '/set_setting_carriers' => 'distributors#set_setting_carriers' 
  
  post '/add_cart' => 'home#add_cart'
  get '/patent' => 'home#patent'
  get '/get_discount'=> 'home#get_discount'
  get '/update_color'=> 'home#update_color'
  post '/create_order' => 'home#create_order'
  post '/create_club_order' => 'home#create_club_order'
  post '/post_enquiry' => 'home#post_enquiry' 
  
  post '/subscribe' => "home#subscribe"
  get '/payment' => 'home#payment'   
  
  post '/get_shipping_carreirs' =>'home#get_shipping_carreirs'
  get '/get_shipping_states' =>'home#get_shipping_states'
  get '/set_shipping_values' => 'home#set_shipping_values'
    
  get '/edit_card' => 'home#edit_card'   
  post '/update_card' => 'home#update_card'
  get '/videos'=>'home#videos'
  
  get '/apply_in_sixty_seconds' => 'home#apply_in_sixty_seconds'   
  
  post '/create_customer' => 'home#create_customer' 
  post '/process_login' => 'home#process_login'
  
  get '/edit_color' => 'home#edit_color'
  post '/update_color' => 'home#update_color'
  
  
  get '/auto_ship' => 'home#auto_ship'
  get '/account_details' => 'home#account_details'
  get '/past_orders' => 'home#past_orders'
  get '/sign_out' => 'home#sign_out'
  get '/login' => 'home#login'
  get 'dashboard' => 'home#dashboard'
  get '/message_thanks' => 'home#message_thanks' 
  #get '/club_details' => 'home#club_details'
  get '/cart' => 'home#cart'
  get '/checkout' => "home#checkout"
  get '/faq' => 'home#faq'
  get '/thankyou' => 'home#thanks'
  
  get '/edit_address'=> 'home#edit_address'
  post '/update_address'=> 'home#update_address'
  
  get '/product_details' => 'home#product_details'
  get '/remove_product_from_cart' => 'home#remove_product_from_cart'
  get '/get_billing_states' => "home#get_billing_states"
  
  get '/products' => 'home#products'
  post '/order_confirmation' => 'home#after_payment'
  
  post '/confirmation' => 'home#after_payment'
    
  post '/save_forum' => 'home#save_forum' 
  post '/thankyou' => 'home#thankyou'
  get '/buy_now' =>"home#buy_now"
  get '/get_total_price' => 'distributors#get_total_price'
   
  post '/get_forums' => 'home#get_forums' 
  get '/new_forum' => 'home#new_forum' 
  get '/get_states' => 'home#get_states'
  get '/add_to_cart' => 'home#add_to_cart'
  get '/remove_from_cart' => 'home#remove_from_cart'
  get '/fibre_hold' => 'home#fibre_hold'
  
  get '/mirror' => 'home#mirror'
  get '/optimizer' => 'home#optimizer'
  
  get '/forum' => 'home#forum'
  get '/more_reviews' => 'home#more_reviews'  
  
  get '/terms' => 'home#terms'
  get '/testimonials' => 'home#testimonials'
  get '/photos' => 'home#photos'
  get '/how_it_works' => 'home#how_it_works'
  get '/what_is_it' => 'home#what_is_it'
  get '/about_us' => 'home#about_us'
  get '/contact_us' => 'home#contact_us'
  get '/color' => 'home#color'
  get '/mens_hair_loss' => 'home#mens_hair_loss'
  get '/womens_hair_loss' => 'home#womens_hair_loss'

  get '/forgot_password' => 'home#forgot_password'
  post '/forgot_password_email' => 'home#forgot_password_email'
  get '/password_reset_success' => 'home#password_reset_success'
  
  resources :orders, only: [:new, :create, :buy_product] do
    collection do
      get :confirmation
      get :buy_product 
    end
  end
   
  

  resources :distributors, only: [:new, :create] do
    collection do
      get :confirmation
      get :show
      get :edit
      put :update
      post :login
      get :logout
      post :order
      get :past_orders
    end
  end

  resources :health_check, only: [:index]

  namespace :admin do
    get "/" => "orders#index"

    resources :customers, only: [:index, :show, :edit, :update] do
      resources :orders, only: [:index, :new, :create]
    end
     
    resources :forums do
    end 
    
    resources :domain_distributors do
      collection do
        post :filter_report 
        get :download_report 
      end 
    end
    
    resources :distributors, except: [:destroy] do
      resources :orders, only: [:index, :new, :create]

      member do
        get :approve
      end
    end

    resources :orders, except: [:destroy]  do
      member do
        put :refund 
      end
      collection do
        get :pull_details_from_shopify 
        get :distributor_orders
      end
    end

    resources :shipments, except: [:destroy]
  end
end

app/models/domain_distributor.rb
class DomainDistributor < ActiveRecord::Base
 
    validates :name, :domain, presence: true 
    has_many :distributor_orders, foreign_key: "distributor_id"   
    validates :domain, uniqueness: true  
  
  def self.update_orders
    order_ids = Order.where(:host=>"tryhairillusion.com").collect(&:id) 
    new_d= DomainDistributor.where("domain='tryhairillusion.com'").first
    new_id = new_d.id 
    distributor_orders = DistributorOrder.where("order_id in (?)",order_ids)
    distributor_orders.each do |s| 
      s.update_attribute(:distributor_id,new_id)
    end
  end 
 
  def self.get_orders  
    logger.info "**************************---here starts updated rake****************************"
    shop_url = "https://a98b179d72117d149e44ae83796e4c64:b62b5da657f75898e1d45eb6a6e0e247@hair-illusion-llc.myshopify.com/admin"
    ShopifyAPI::Base.site = shop_url  
    total_pages = 15
    customers_list = []
    (1..15).each do |page| 
      customers = ShopifyAPI::Customer.all( params: {limit: 250, page: page, status: 'any' })  
       customers.each do |c|  
         customers_list << c
       end
    end 
    i = 0
    (1..15).each do |page| 

    customers_list.each do |c|  
      email = c.email
      db_customer = Customer.find_by_email(email) 
       address = c.default_address 
      if db_customer.nil? 
        i = i+1
        logger.info address.inspect
        state = "not mentioned"
        if address.province
          state = address.province 
          state = "not mentioned" if state.nil?
        end 
        
        zip_value = address.zip
        zip_value = "not mentioned" if zip_value.blank?
        customer = Customer.new(:email=>email, :first_name=>c.first_name, :last_name=>c.last_name, :address1 => address.address1,:address2 => address.address2, :created_at=>c.created_at,
        :city=> address.city, :country =>address.country_code, :state=>state, :zip=>zip_value, :stripe_id=>"shopify"+Time.now.to_i.to_s+i.to_s, :shopify_customer_id=>c.id)
        
        customer.save(validate=> false)    
      else   
        state = "not mentioned"
        if address.province
          state = address.province 
          state = "not mentioned" if state.nil?
        end 
        address = c.default_address
        db_customer.shopify_customer_id = c.id 
        db_customer.first_name = c.first_name
        db_customer.last_name=c.last_name
        db_customer.address1=address.address1
        db_customer.address2=address.address2
        db_customer.city=address.city
        db_customer.country =address.country_code
        db_customer.state =state
        if address.zip && !address.zip.blank?
          db_customer.zip =address.zip  
        else
          db_customer.zip = "not mentioned"
        end
        
        db_customer.save(validate: false) 
        customer = db_customer
      end
    end 
    
    orders = ShopifyAPI::Order.all( params: {limit: 250, page: page, status: 'any' })   
    
    orders.each do |o|   
      distributor_order = nil 
      order = Order.find_by_shopify_order_id(o.id)
      if order.nil? 
        customer = Customer.find_by_shopify_customer_id(o.customer.id) 
        customer_id = customer.id 
        
        order = Order.new(:orderer_id=>customer_id, :orderer_type=>'Customer', :shopify_order_id=>o.id, :created_at=>o.processed_at)
        order.save
        
        host = ""
        landing_site = o.landing_site
        landing_site = "" if landing_site.nil?
        
        if landing_site.include?('hairillusion.net')
          host = "hairillusion.net" 
          distributor = DomainDistributor.where(:domain=>"hairillusion.net").first
          if distributor
            distributor_order = DistributorOrder.new(:distributor_id=>distributor.id, :order_id=>order.id, :created_at=>order.created_at)
            distributor_order.save
          end
        elsif landing_site.include?('buyhairillusion.com') 
          host = "buyhairillusion.com" 
          distributor = DomainDistributor.where(:domain=>"buyhairillusion.com").first
          if distributor
            distributor_order = DistributorOrder.new(:distributor_id=>distributor.id, :order_id=>order.id, :created_at=>order.created_at)
            distributor_order.save
          end
        elsif landing_site.include?('gethairillusion.com') 
          host = 'gethairillusion.com'
          distributor = DomainDistributor.where(:domain=>"gethairillusion.com").first
          if distributor
            distributor_order = DistributorOrder.new(:distributor_id=>distributor.id, :order_id=>order.id, :created_at=>order.created_at)
            distributor_order.save
          end 
        elsif landing_site.include?('facebook.com') 
          host = 'facebook.com'
          distributor = DomainDistributor.where(:domain=>"facebook.com").first
          if distributor
            distributor_order = DistributorOrder.new(:distributor_id=>distributor.id, :order_id=>order.id, :created_at=>order.created_at)
            distributor_order.save
          end           
        elsif (landing_site.include?('hairillusion.com') && !landing_site.include?('tryhairillusion.com'))
          host = 'hairillusion.com'
          distributor = DomainDistributor.where(:domain=>"hairillusion.com").first
          if distributor
            distributor_order = DistributorOrder.new(:distributor_id=>distributor.id, :order_id=>order.id, :created_at=>order.created_at)
            distributor_order.save
          end 
        elsif (landing_site.include?('hairillusionllc.com'))
          host = 'hairillusionllc.com'
          distributor = DomainDistributor.where(:domain=>"hairillusionllc.com").first
          if distributor
            distributor_order = DistributorOrder.new(:distributor_id=>distributor.id, :order_id=>order.id, :created_at=>order.created_at)
            distributor_order.save
          end 
        elsif (landing_site.include?('hairisthere.com'))
          host = 'hairisthere.com'
          distributor = DomainDistributor.where(:domain=>"hairisthere.com").first
          if distributor
            distributor_order = DistributorOrder.new(:distributor_id=>distributor.id, :order_id=>order.id, :created_at=>order.created_at)
            distributor_order.save
          end 
        elsif (landing_site.include?('hairillusionmagic.com'))
          host = 'hairillusionmagic.com'
          distributor = DomainDistributor.where(:domain=>"hairillusionmagic.com").first
          if distributor
            distributor_order = DistributorOrder.new(:distributor_id=>distributor.id, :order_id=>order.id, :created_at=>order.created_at)
            distributor_order.save
          end 
        elsif (landing_site.include?('tryhairillusion.com'))
          host = 'tryhairillusion.com'
          distributor = DomainDistributor.where(:domain=>"tryhairillusion.com").first
          if distributor
            distributor_order = DistributorOrder.new(:distributor_id=>distributor.id, :order_id=>order.id, :created_at=>order.created_at)
            distributor_order.save
          end
        elsif (landing_site.include?('hairillusion4you.com'))
          host = 'hairillusion4you.com'
          distributor = DomainDistributor.where(:domain=>"hairillusion4you.com").first
          if distributor
            distributor_order = DistributorOrder.new(:distributor_id=>distributor.id, :order_id=>order.id, :created_at=>order.created_at)
            distributor_order.save
          end
        elsif (landing_site.include?('hairillusionmagic.com'))
          host = 'hairillusionmagic.com'
          distributor = DomainDistributor.where(:domain=>"hairillusionmagic.com").first
          if distributor
            distributor_order = DistributorOrder.new(:distributor_id=>distributor.id, :order_id=>order.id, :created_at=>order.created_at)
            distributor_order.save
          end
        else  
          DomainDistributor.all.each do |d| 
            if landing_site.include?(d.domain) && d.domain != 'hairillusion.com'
              distributor_order = DistributorOrder.new(:distributor_id=>d.id, :order_id=>order.id, :created_at=>order.created_at)
              distributor_order.save
              host = "#{d.domain}"   
            end  
          end
          #if order has blank referer
          if distributor_order.nil? 
            distributor = DomainDistributor.where(:domain=>"hairillusion.net").first
            if distributor
              distributor_order = DistributorOrder.new(:distributor_id=>distributor.id, :order_id=>order.id, :created_at=>order.created_at)
              distributor_order.save
              host = "hairillusion.net"   
            end 
          end 
        end   
        
        order.update_attribute(:host,host)  
        o.line_items.each do |item| 
          if item.title == "Hair Illusion Fiber Hold Spray"
            product = Product.where("description = ?", "Hair Illusion Fiber Hold Spray").first  
          else 
            product = Product.where("sku = ?", item.sku).first  
          end 
          product_id = nil 
          product_id = product.id unless product.nil?   
          price = item.price.to_f*100 
          order_item = OrderItem.new(:quantity=>item.quantity, :price=>price, :order_id=>order.id,:product_id=>product_id )  
          order_item.save!   
        end     
        OrderMailer.send_order_email(distributor_order.distributor_id, distributor_order.order_id).deliver!
        
      end 
      end 
    end 
  end
    
end

app/controllers/admin/domain_distributors_controller.rb
class Admin::DomainDistributorsController < Admin::ApplicationController 
  before_action :set_admin_domain_distributor, only: [:show, :edit, :update, :destroy]

  # GET /admin/domain_distributors
  def index
    @domain_distributors = DomainDistributor.all.order("created_at desc").page(params[:page]).per_page(10)
  end

  # GET /admin/domain_distributors/1
  def show
    @distributor_orders = @domain_distributor.distributor_orders.order("DATE(created_at) DESC").page(params[:page]).per_page(10)
  end
  
  def download_report   
    @domain_distributor = DomainDistributor.find params[:distributor_id]
    @distributor_orders = @domain_distributor.distributor_orders.where("DATE(created_at) >= ? and DATE(created_at) <=?", params[:start_date].to_datetime.utc ,params[:end_date].to_datetime.utc).order("DATE(created_at) DESC") 
    render :pdf => "#{@domain_distributor.name}", :layout => 'pdf.html.erb'   
  end

  # GET /admin/domain_distributors/new
  def new
    @domain_distributor = DomainDistributor.new
  end

  # GET /admin/domain_distributors/1/edit
  def edit
  end
  
  def filter_report
    @domain_distributor = DomainDistributor.find params[:domain_distributor_id] 
    @distributor_orders = @domain_distributor.distributor_orders.where("DATE(created_at) >= ? and DATE(created_at) <=?", params[:search][:start_date].to_datetime.utc ,params[:search][:end_date].to_datetime.utc).order("DATE(created_at) DESC").page(params[:page]).per_page(10)
  end

  # POST /admin/domain_distributors
  def create
    @domain_distributor = DomainDistributor.new(domain_distributor_params)

    if @domain_distributor.save
      redirect_to '/admin/domain_distributors', notice: 'Domain distributor was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /admin/domain_distributors/1
  def update
    if @domain_distributor.update(domain_distributor_params)
       redirect_to '/admin/domain_distributors', notice: 'Domain distributor was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /admin/domain_distributors/1
  def destroy
    @domain_distributor.destroy
    redirect_to admin_domain_distributors_url, notice: 'Domain distributor was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_domain_distributor
      @domain_distributor = DomainDistributor.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def domain_distributor_params
      params.require(:domain_distributor).permit(:domain, :name, :company_name, :email, :percentage, :phone, :address, :state, :country, :zip)
    end
end

app/views/admin/domain_distributors/_form.html.erb
<style>
	.add_table td {
		padding: 3px
	}
</style>

<%= form_for @domain_distributor, url: @domain_distributor.new_record? ? admin_domain_distributors_path : admin_domain_distributor_path(@domain_distributor), html: { class: 'form-horizontal' } do |f| %>

<% if @domain_distributor.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@domain_distributor.errors.count, "error") %> prohibited this admin_domain_distributor from being saved:</h2>

	<ul>
		<% @domain_distributor.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<table class="add_table">
	<tr>
		<td><b>Name:</b></td>
		<td> <%= f.text_field :name, :required=>true %> </td>

		<td><b>Company:</b></td>
		<td> <%= f.text_field :company_name, :required=>true %> </td>

		<td><b>Domain Name:</b></td>
		<td> <%= f.text_field :domain, :required=>true %> </td>
	</tr>

	<tr>
		<td><b>Email:</b></td>
		<td> <%= f.email_field :email, :required=>true %> </td>

		<td><b>Percentage:</b></td>
		<td> <%= f.number_field :percentage, :required=>true %> </td>

		<td><b>Phone:</b></td>
		<td> <%= f.text_field :phone, :required=>true %> </td>

	</tr>

	<tr>
		<td style="vertical-align: top"><b>Address:</b></td>
		<td colspan="2"> <%= f.text_area :address, :style=>"width:300px;height:100px;" %> </td>

		<td style="vertical-align: top" colspan="2">
		<div>
			<div>
				<b>State:</b>
				<%= f.text_field :state, :required=>true %>
			</div>
			<br />
			<div>
				<b>Country:</b>
				<%= f.text_field :country, :required=>true, :style=>"display:inline-block" %>
			</div>

		</div></td>
	</tr>

	<tr>

		<td><b>Zip:</b></td>
		<td> <%= f.text_field :zip, :required=>true %> </td>

	</tr>

</table>

<br />
<div class="actions">
	<%= f.submit "Save", :class=>"btn btn-primary" %>
	<%= link_to 'Back', admin_domain_distributors_path, :class=>"btn btn-default" %>
</div>
<br />
<br />
<br />
<% end %>

app/views/admin/domain_distributors/_orders_list.html.erb
 
<b>Comission on below orders: $<%= number_with_precision(get_commission(distributor_orders), :precision => 2) %> </b>
<br />
<%= will_paginate distributor_orders, :container => false %>
<br />
<table class="table table-striped table-bordered table-hover table-condensed grid-table">
	<tr>
		<th>Date</th> 
		<th>Customer</th>
		<th>Details</th>
	</tr>
	<% distributor_orders.each do |order| %>
		<tr>
			<td>
				<%= order.created_at.strftime("%d/%m/%Y at %H:%M") %>
			</td>
			<td> 
				<%="#{order.try(:order).try(:orderer).try(:name)}"%> 
			</td>
			<td>  
				<% if order.try(:order) %>
					<%= link_to("Details", admin_order_path(order.try(:order))) %> 
				<%end%>
			</td>
		</tr>
	<%end%>
</table> 

<%= will_paginate distributor_orders, :container => false %>

app/views/admin/domain_distributors/download_report.html.erb
<h4> Client Name: <%= @domain_distributor.name%></h4>
<h4> Email Address: <%= @domain_distributor.email%></h4>
<h4> Company Name: <%= @domain_distributor.company_name %></h4>
<h4> Domain Name: <%= @domain_distributor.domain%></h4>

<b>Comission for orders from <%= params[:start_date]%> to <%= params[:end_date]%> is: $<%= number_with_precision(get_commission(@distributor_orders), :precision => 2) %> </b>
<br />
<br />
<b>Total sales from <%= params[:start_date]%> to <%= params[:end_date]%> is: $<%= number_with_precision(get_total_sales(@distributor_orders), :precision => 2) %> </b>

<br />
<br />

<table border="1" bordercolor="#ccc">
	<tr>
		<th>Date</th>
		<th>Customer</th>
		<th>Name</th>
		<th>Qty</th>
		<th>Price</th>
	</tr>
	<% @distributor_orders.each do |order| %> 
	
		<% order.order.order_items.each do |order_item| %>
            <tr>
				<td style="padding:5px"> <%= order.order.created_at.strftime("%d/%m/%Y at %H:%M") %> </td>
				<td style="padding:5px"> <%= order_item.try(:order).try(:orderer).try(:name) %> </td>
				<td style="padding:5px"> <%=order_item.try(:product).try(:description)%> </td>
				<td style="padding:5px"> <%=order_item.quantity%> </td>
				<td style="padding:5px"> <%= number_to_currency( (order_item.price*order_item.quantity) / 100.0) %> </td>
			</tr>
          <% end %> 
	<%end%>
</table>

app/views/admin/domain_distributors/edit.html.erb
<h4>Editing domain distributor</h4>

<%= render 'form' %> 

app/views/admin/domain_distributors/filter_report.js.erb
$("#reports_list_div").html("<%= escape_javascript(render(:partial => 'orders_list', :locals => {:distributor_orders => @distributor_orders})) %>");

app/views/admin/domain_distributors/index.html.erb
<h4>Domain distributors</h4>

<table class="table table-striped table-bordered table-hover table-condensed grid-table" data-url="<%= admin_domain_distributors_path %>">
  <thead>
    <tr>
      <th>Name</th>
      <th>Company</th>
      <th>Email</th>
      <th>Percentage</th>
      <th>Domain</th>
      <th>Address</th> 
      <th>Country</th>
      <th>Zip</th>
      <th></th>
      <th></th> 
    </tr>
  </thead>

  <tbody>
    <% @domain_distributors.each do |admin_domain_distributor| %>
      <tr>
        <td><%= admin_domain_distributor.name %></td>
        <td><%= admin_domain_distributor.company_name %></td>
        <td><%= admin_domain_distributor.email %></td>
        <td><%= admin_domain_distributor.percentage %></td>
        <td><%= admin_domain_distributor.domain %></td>
        <td><%= admin_domain_distributor.address %></td> 
        <td><%= admin_domain_distributor.country %></td>
        <td><%= admin_domain_distributor.zip %></td>
        <td><%= link_to 'Details', "/admin/domain_distributors/#{admin_domain_distributor.id}" %></td>
        <td><%= link_to 'Edit', edit_admin_domain_distributor_path(admin_domain_distributor) %></td> 
      </tr>
    <% end %>
  </tbody> 
</table> 
<%= link_to 'New Distributor', new_admin_domain_distributor_path, :class=>"btn btn-primary" %>
<br />
<div class="pagination-center">
	<%= will_paginate @domain_distributors  %>
</div>

app/views/admin/domain_distributors/new.html.erb
<h4>New domain distributor</h4>

<%= render 'form' %> 

app/views/admin/domain_distributors/show.html.erb
 
<%= link_to 'Back', admin_domain_distributors_path, :class=>"btn btn-default" %>
<br />
<br />
<table class="table table-striped table-bordered table-hover table-condensed grid-table">
	<tr>
		<td><b>Name:</b></td>
		<td> <%= @domain_distributor.name%> </td>

		<td><b>Company:</b></td>
		<td> <%= @domain_distributor.company_name%> </td>

		<td><b>Domain Name:</b></td>
		<td> <%= @domain_distributor.domain%> </td>
	</tr>

	<tr>
		<td><b>Email:</b></td>
		<td> <%= @domain_distributor.email%> </td>

		<td><b>Percentage:</b></td>
		<td> <%= @domain_distributor.percentage%> </td>

		<td><b>Phone:</b></td>
		<td> <%= @domain_distributor.phone%> </td>

	</tr>

	<tr>
		<td style="vertical-align: top"><b>Address:</b></td>
		<td colspan="3"> <%= @domain_distributor.address.html_safe %> </td>

		<td ><b>State:</b></td>
		<td> <%= @domain_distributor.state %> </td>
	</tr>
	
	<tr>
		<td style="vertical-align: top"><b>Country:</b></td>
		<td> <%= @domain_distributor.country %> </td>

		<td ><b>Zip:</b></td>
		<td> <%= @domain_distributor.zip %> </td>
		<td></td>
		<td></td>
	</tr> 
</table>

<h3> Orders from <%= @domain_distributor.domain %></h3> 

<%= form_for :search, :url => { :controller=>'admin/domain_distributors', :action => 'filter_report' }, html: {class: 'form form-horizontal', style:'margin:0px;left:0px;' }, :method => :post, :remote=>true do |f|%>
<div class="well" style="width: 100%"> 
	<%= hidden_field_tag :domain_distributor_id, @domain_distributor.id %>
	<table align="center" class="quick_search_table" >
		<tr> 
 			<td style="width: 55px;padding-left: 5px"> Start: </td>
			<td style="width: 140px"> <%= f.text_field :start_date, :value => DateTime.now.to_date.strftime('%d/%m/%Y'), :class => "datepicker",:readonly=>true %> </td>
			<td style="width: 55px;padding-left: 5px"> End: </td>
			<td style="width: 140px"> <%= f.text_field :end_date, :value => DateTime.now.to_date.strftime('%d/%m/%Y'), :class => "datepicker",:readonly=>true %> </td>		
			<td style="width: 100%;padding-left: 50px"> <%= f.submit "Filter", :class=>"btn btn-primary", "data-disable-with"=>"Wait..." %> </td>
			<td> <%= link_to "Download as Xlsx", "#", :onclick=>"onDowloadReport()", :class=>"btn btn-success"%></td>			
		</tr>
	</table>
</div>
<%end%>  

<div id="reports_list_div">
	<%= render :partial => "orders_list", :locals => {:distributor_orders => @distributor_orders } %> 
</div>  

<script type="text/javascript">

  $(document).ready(function(){
    $('.datepicker').datepicker({format: 'dd/mm/yyyy',"autoclose" : true});
  });
  
  function onDowloadReport()
  {  
	params = "start_date="+$("#search_start_date").val()+"&end_date="+$("#search_end_date").val()+"&distributor_id="+$("#domain_distributor_id").val();		
	window.location.href = '<%=download_report_admin_domain_distributors_path%>'+"?"+params; 
  }
</script>
  	 