config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Hairillusion::Application.routes.draw do 

  root 'home#index'

  mount Sidekiq::Web => '/sidekiq'
  
  get '/distributors/subregion_options' => 'distributors#subregion_options' 
  get '/set_setting_carriers' => 'distributors#set_setting_carriers' 
  
  post '/add_cart' => 'home#add_cart'
  get '/patent' => 'home#patent'
  get '/get_discount'=> 'home#get_discount'
  get '/update_color'=> 'home#update_color'
  post '/create_order' => 'home#create_order'
  post '/create_club_order' => 'home#create_club_order'
  post '/post_enquiry' => 'home#post_enquiry' 
  
  post '/subscribe' => "home#subscribe"
  get '/payment' => 'home#payment'   
  
  post '/get_shipping_carreirs' =>'home#get_shipping_carreirs'
  get '/get_shipping_states' =>'home#get_shipping_states'
  get '/set_shipping_values' => 'home#set_shipping_values'
    
  get '/edit_card' => 'home#edit_card'   
  post '/update_card' => 'home#update_card'
  get '/videos'=>'home#videos'
  
  get '/apply_in_sixty_seconds' => 'home#apply_in_sixty_seconds'   
  
  post '/create_customer' => 'home#create_customer' 
  post '/process_login' => 'home#process_login'
  
  get '/edit_color' => 'home#edit_color'
  post '/update_color' => 'home#update_color'
  
  
  get '/auto_ship' => 'home#auto_ship'
  get '/account_details' => 'home#account_details'
  get '/past_orders' => 'home#past_orders'
  get '/sign_out' => 'home#sign_out'
  get '/login' => 'home#login'
  get 'dashboard' => 'home#dashboard'
  get '/message_thanks' => 'home#message_thanks' 
  #get '/club_details' => 'home#club_details'
  get '/cart' => 'home#cart'
  get '/checkout' => "home#checkout"
  get '/faq' => 'home#faq'
  get '/thankyou' => 'home#thanks'
  
  get '/edit_address'=> 'home#edit_address'
  post '/update_address'=> 'home#update_address'
  
  get '/product_details' => 'home#product_details'
  get '/remove_product_from_cart' => 'home#remove_product_from_cart'
  get '/get_billing_states' => "home#get_billing_states"
  
  get '/products' => 'home#products'
  post '/order_confirmation' => 'home#after_payment'
  
  post '/confirmation' => 'home#after_payment'
    
  post '/save_forum' => 'home#save_forum' 
  post '/thankyou' => 'home#thankyou'
  get '/buy_now' =>"home#buy_now"
  get '/get_total_price' => 'distributors#get_total_price'
   
  post '/get_forums' => 'home#get_forums' 
  get '/new_forum' => 'home#new_forum' 
  get '/get_states' => 'home#get_states'
  get '/add_to_cart' => 'home#add_to_cart'
  get '/remove_from_cart' => 'home#remove_from_cart'
  get '/fibre_hold' => 'home#fibre_hold'
  
  get '/mirror' => 'home#mirror'
  get '/optimizer' => 'home#optimizer'
  
  get '/forum' => 'home#forum'
  get '/more_reviews' => 'home#more_reviews'  
  
  get '/terms' => 'home#terms'
  get '/testimonials' => 'home#testimonials'
  get '/photos' => 'home#photos'
  get '/how_it_works' => 'home#how_it_works'
  get '/what_is_it' => 'home#what_is_it'
  get '/about_us' => 'home#about_us'
  get '/contact_us' => 'home#contact_us'
  get '/color' => 'home#color'
  get '/mens_hair_loss' => 'home#mens_hair_loss'
  get '/womens_hair_loss' => 'home#womens_hair_loss'

  get '/forgot_password' => 'home#forgot_password'
  post '/forgot_password_email' => 'home#forgot_password_email'
  get '/password_reset_success' => 'home#password_reset_success'
  
  resources :orders, only: [:new, :create, :buy_product] do
    collection do
      get :confirmation
      get :buy_product 
    end
  end
   
  

  resources :distributors, only: [:new, :create] do
    collection do
      get :confirmation
      get :show
      get :edit
      put :update
      post :login
      get :logout
      post :order
      get :past_orders
    end
  end

  resources :health_check, only: [:index]

  namespace :admin do
    get "/" => "orders#index"

    resources :customers, only: [:index, :show, :edit, :update] do
      resources :orders, only: [:index, :new, :create]
    end
     
    resources :forums do
    end 
    
    resources :domain_distributors do
      collection do
        post :filter_report 
        get :download_report 
      end 
    end
    
    resources :distributors, except: [:destroy] do
      resources :orders, only: [:index, :new, :create]

      member do
        get :approve
      end
    end

    resources :orders, except: [:destroy]  do
      member do
        put :refund 
      end
      collection do
        get :pull_details_from_shopify 
        get :distributor_orders
      end
    end

    resources :shipments, except: [:destroy]
  end
end

app/models/distributor.rb
class Distributor < ActiveRecord::Base
  extend GridTable

  attr_accessor :skip_password_required

  has_many :orders, as: :orderer, dependent: :destroy

  has_secure_password

  validates :company_name, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, presence: true
  validates :address1, presence: true
  validates :city, presence: true
  validates :country, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  validates :price, presence: true
  validates :tax_info, presence: true
  
  validates :email, presence: true,
                    uniqueness: true,
                    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create }

  validates :password, presence: true, confirmation: true, length: { minimum: 6 }, if: :password_required?
  validates :password_confirmation, presence: true, if: :password_required?

  grid_table_control :company_name
  grid_table_control :city
  grid_table_control :state
  grid_table_control :price
  grid_table_control :created_at

  before_validation(on: :create) do
    if self.password.blank?
      self.password = "hairillusion"
      self.price = 5995
      self.password_confirmation = self.password
    end
  end
  
  def name
    return "#{first_name} #{last_name}"
  end

  private
  def password_required?
    self.require_password_reset && !skip_password_required
  end
end

app/controllers/admin/distributors_controller.rb
class Admin::DistributorsController < Admin::ApplicationController
  respond_to :html
  respond_to :js, only: [:index]

  def index
    respond_to do |format|
      format.html {}
      format.js do
        @distributors = Distributor.all

        grid_table_for(@distributors, index_params)
      end
    end
  end

  def show
    @distributor = Distributor.find(params[:id])
  end

  def new
    @distributor = Distributor.new
  end

  def create
    @distributor = Distributor.new(distributor_params)

    if @distributor.save
      redirect_to admin_distributor_path(@distributor)
    else
      render :new
    end
  end

  def edit
    @distributor = Distributor.find(params[:id])
  end

  def update
    @distributor = Distributor.find(params[:id])
    @distributor.skip_password_required = true

    if @distributor.update_attributes(distributor_params)
      redirect_to admin_distributor_path(@distributor)
    else
      render :edit
    end
  end

  def approve
    @distributor = Distributor.find(params[:id]) 
    stripe_customer = Stripe::Customer.create(
      email: @distributor.email
    ) 
    password = "hairillusion" 
    if @distributor.update_attributes(password: password, password_confirmation: password, require_password_reset: true, approved: true, stripe_id: stripe_customer.id)
      DistributorMailer.approved(@distributor, password).deliver! 
      redirect_to admin_distributor_path(@distributor)
    else
      render :show
    end
  end

  private
  def index_params
    params.permit [].concat(Distributor.grid_table_strong_params)
  end

  def distributor_params
    distributor_params = params.require(:distributor).permit(:country,:company_name, :first_name, :last_name, :tax_id, :email, :phone, :address1, :address2, :city, :state, :zip, :price)
    distributor_params[:price] = distributor_params[:price].to_f * 100 unless distributor_params[:price].blank?

    distributor_params
  end
end

app/controllers/distributors_controller.rb
class DistributorsController < ApplicationController
  before_action :login_required, only: [:show, :edit, :update]
  #before_action :reset_password_required, except: [:edit, :update, :logout] 
  layout 'application'
  
  def new
    @distributor = Distributor.new
        @error = ""
  end
  
  def subregion_options
    render partial: 'subregion_select'
  end
  
  def set_setting_carriers
    
    shipping_arr = params[:value].split("____")  
    session[:shipping_price] = shipping_arr[0].to_f
    
    
    shipping_code = shipping_arr[1]
    session[:country_shipping_code] = shipping_arr[1] 
    
    @shipping_name = shipping_code
    @shipping = shipping_arr[0].to_f
  end
  

  def get_total_price
    @distributor = Distributor.find params[:distributor_id].to_i
    total_qty = 0
    @total_price = 0
    @shipping = 0 
    params[:products].each do |p|  
      if p[1][:qty].to_i > 0
        total_qty += p[1][:qty].to_i
        dpp = DistributorProductPrice.where("distributor_id=? and distributor_product_id=?", @distributor.id, p[1][:product_id].to_i).first
        if dpp 
          @total_price += (p[1][:qty].to_i * dpp.price)
        end
      end 
    end 
    @total_price = @total_price.round(2)
    if @distributor.country && @distributor.country.downcase == "us"
      @shipping = 25
    else
      @shipping = 50
    end
 
    @subtotal = @total_price 
    @total_price = @total_price + @shipping 
    @total_price = @total_price.round(2)
  end
  
  def create
    @distributor = Distributor.new(distributor_params)
      
    if @distributor.save 
      distributor_products = DistributorProduct.all 
      
      distributor_products.each do |dp|
        price = 0
        if ["Jet Black 38g", "Black 38g", "Dark Brown 38g", "Brown 38g", "Light Brown 38g", "Auburn 38g", "Blonde 38g", "Light Blonde 38g"].include?(dp.name)
          price = 22.50
        elsif ["Jet Black 18g", "Black 18g", "Dark Brown 18g", "Brown 18g", "Light Brown 18g", "Auburn 18g", "Blonde 18g", "Light Blonde 18g"].include?(dp.name)
          price = 15.00
        elsif ["Mirror"].include?(dp.name)
          price = 12.00 
        elsif ["Optimizer"].include?(dp.name)
          price = 2.50  
        elsif ["Fibre Hold Spray"].include?(dp.name)
          price = 12.00  
        elsif ["Spray Applicator"].include?(dp.name)
          price = 20.00
        elsif ["Water Resistant Spray"].include?(dp.name)
          price = 19.00     
        elsif ["Black 6g"].include?(dp.name)
          price = 7.50    
        end  
        distributor_product_price = DistributorProductPrice.create(:distributor_id=>@distributor.id,:distributor_product_id=>dp.id, :price=>price)
      end 
      DistributorMailer.new_distributor_notification(@distributor).deliver! 
      DistributorMailer.new_distributor_admin_notification(@distributor).deliver! 

      redirect_to confirmation_distributors_path
    else
      render new_distributor_path
    end
  end

  def show
    @distributor = current_distributor
    @order = @distributor.orders.build
    @credit_card = CreditCard.new

    DistributorProductPrice.where(:distributor_id=>@distributor.id).each do |p| 
      @order.order_items<< OrderItem.new(product: p.distributor_product, quantity: 0, product_type: 'DistributorProduct')
    end
    
  end

  def edit
    @distributor = current_distributor
  end

  def update
    @distributor = current_distributor

    if @distributor.update_attributes(distributor_params)
      @distributor.update_attribute(:require_password_reset, false)
      redirect_to distributors_path
    else
      render :edit
    end
  end

  def confirmation
  end 

  def login
     @error = ""
    @distributor = Distributor.find_by_email(params[:email])
    if @distributor.present? && @distributor.authenticate(params[:password])
      session[:distributor_id] = @distributor.id
      redirect_to distributors_path
    else
      @distributor = Distributor.new if @distributor.nil?
      @error = "Invalid email or password, Please click forgot password if you forgot your password."  
      render :new
    end
  end

  def logout
    reset_session
    redirect_to '/'
  end

  private
  def distributor_params
    params.require(:distributor).permit(:company_name, :country, :first_name, :last_name, :tax_info, :address1, :address2, :city, :state, :zip, :phone, :email, :password, :password_confirmation)
  end

  def current_distributor
    @current_distributor ||= Distributor.find(session[:distributor_id]) if session[:distributor_id]
  end

  def logged_in?
    current_distributor
  end

  def login_required
    redirect_to new_distributor_path unless logged_in?
  end

  def redirect_to_target_or_default(default, *args)
    redirect_to(session[:return_to] || default, *args)
    session[:return_to] = nil
  end

  def store_target_location
    # don't store the target location for SignUp and Login
    unless request.path == new_distributor_path
      session[:return_to] = request.url if request.get? && request.format == :html
    end
  end

  def reset_password_required
    if logged_in? && current_distributor.require_password_reset
      store_target_location
      redirect_to edit_distributors_path, :alert => 'You must update your password'
    end
  end
end

app/views/admin/distributors/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <h2>Distributor Form</h2>

    <%= form_for @distributor, url: @distributor.new_record? ? admin_distributors_path : admin_distributor_path(@distributor), html: { class: 'form-horizontal' } do |f| %>
      <%= control_group(@distributor, :company_name, label: 'Company') do %>
        <%= f.text_field :company_name, class: 'form-control required' %>
      <% end %>

      <%= control_group(@distributor, :first_name, label: 'First Name') do %>
        <%= f.text_field :first_name, class: 'form-control required' %>
      <% end %>

      <%= control_group(@distributor, :last_name, label: 'Last Name') do %>
        <%= f.text_field :last_name, class: 'form-control required' %>
      <% end %>

      <%= control_group(@distributor, :email, label: 'Email') do %>
        <%= f.email_field :email, class: 'form-control required' %>
      <% end %>

      <%= control_group(@distributor, :phone, label: 'Phone') do %>
        <%= f.phone_field :phone, class: 'form-control required' %>
      <% end %>

      <%= control_group(@distributor, :address1, label: 'Address') do %>
        <%= f.text_field :address1, class: 'form-control' %>
      <% end %>

      <%= control_group(@distributor, :address2, label: 'Address 2') do %>
        <%= f.text_field :address2, class: 'form-control' %>
      <% end %>
   
      <%= control_group(@distributor, :country, label: 'Country') do %>
        <%= f.country_select :country, {prompt: 'Please select a country'}, { class: 'form-control required' } %>
      <% end %> 
      
      <%= control_group(@distributor, :state, label: 'State/Region/Province') do %> 
        <%= render partial: 'subregion_select', locals: {parent_region: f.object.country} %>
      <% end %>

      <%= control_group(@distributor, :city, label: 'City') do %>
        <%= f.text_field :city, class: 'form-control' %>
      <% end %>
      
      <%= control_group(@distributor, :zip, label: 'Postal/Zip Code') do %>
        <%= f.text_field :zip, class: 'form-control' %>
      <% end %>

      <%= control_group(@distributor, :price, label: 'Price') do %>
        <%= f.number_field :price, value: @distributor.price / 100.0, min: 0, step: 0.01, class: 'form-control' %>
      <% end %>

      <div class="form-group">
        <%= f.submit nil, class: 'btn btn-sm btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/distributors/_row.html.erb
<tr>
  <td><%= distributor.company_name %></td>
  <td><%= distributor.city %></td>
  <td><%= distributor.state %></td>
  <td><%= number_to_currency(distributor.price / 100.0) %></td>
  <td><%= distributor.created_at %></td>
  <td align="center"><%= '&#x2713;'.html_safe if distributor.approved %></td>
  <td>
    <%= link_to icon_text('Details', 'glyphicon glyphicon-info-sign'), admin_distributor_path(distributor), class: 'btn btn-sm btn-success' %>
    <%= link_to icon_text('Edit', 'glyphicon glyphicon-pencil'), edit_admin_distributor_path(distributor), class: 'btn btn-sm btn-primary' %>
  </td>
</tr>

app/views/admin/distributors/_subregion_select.html.erb
<div id="distributor_state_code_wrapper">
  <% parent_region ||= params[:parent_region] %>
  <% country = Carmen::Country.coded(parent_region) %>

  <% if country.nil? %>
    <em>Please select a country above</em>
  <% elsif country.subregions? %>
    <%= subregion_select(:distributor, :state, parent_region,{},{:class=>' form-control'} ) %>
  <% else %>
    <%= text_field(:distributor, :state) %>
  <% end %>
</div>

app/views/admin/distributors/edit.html.erb
<%= render partial: 'form' %>

app/views/admin/distributors/index.html.erb
<table class="table table-striped table-bordered table-hover table-condensed grid-table" data-url="<%= admin_distributors_path %>">
  <thead>
    <tr>
      <th data-field="company_name" data-sort="true" data-default-sort="asc">Company</th>
      <th data-field="city" data-sort="true">City</th>
      <th data-field="state" data-sort="true">State</th>
      <th data-field="price" data-sort="true">Price</th>
      <th data-field="created_at" data-sort="true">Created</th>
      <th>Approved</th>
      <th><%= link_to icon_text('New Distributor', 'glyphicon glyphicon-plus'), new_admin_distributor_path, class: 'btn btn-sm btn-primary' %></th>
    </tr>
    <tr class="filters">
      <th class="filter">
        <%= text_field_tag :filter_company_name, nil, 'data-field' => 'company_name', class: 'row-filter' %>
      </th>
      <th class="filter">
        <%= text_field_tag :filter_city, nil, 'data-field' => 'city', class: 'row-filter', size: 10 %>
      </th>
      <th class="filter">
        <%= text_field_tag :filter_state, nil, 'data-field' => 'state', class: 'row-filter', size: 10 %>
      </th>
      <th class="filter">
        <%= text_field_tag :filter_price, nil, 'data-field' => 'price', class: 'row-filter', size: 10 %>
      </th>
      <th class="filter">
        <%= text_field_tag :filter_created_at, nil, 'data-field' => 'created_at', class: 'row-filter' %>
      </th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody></tbody>
  <tfoot>
    <tr>
      <th colspan="7">
        <%= render 'admin/shared/grid_pager' %>
      </th>
    </tr>
  </tfoot>
</table>

app/views/admin/distributors/new.html.erb
<%= render partial: 'form' %>

app/views/admin/distributors/show.html.erb
<div class="row">
  <div class="col-md-6 well">
    <p>
      <strong>Company Name:</strong>
      <%= @distributor.company_name %>
    <p>

    <p>
      <strong>First Name:</strong>
      <%= @distributor.first_name %>
    <p>

    <p>
      <strong>Last Name:</strong>
      <%= @distributor.last_name %>
    <p>

    <p>
      <strong>Email:</strong>
      <%= mail_to(@distributor.email) %>
    <p>

    <p>
      <strong>Phone:</strong>
      <%= number_to_phone(@distributor.phone) %>
    <p>

    <p>
      <strong>Address1:</strong>
      <%= @distributor.address1 %>
    <p>

    <p>
      <strong>Address2:</strong>
      <%= @distributor.address2 %>
    <p>

    <p>
      <strong>Country:</strong>
      <%= get_country_name(@distributor.country, true) %>
    <p>
    	
	<p>
      <strong>State:</strong>
      <%= @distributor.state %>
    <p>
    	
    <p>
      <strong>City:</strong>
      <%= @distributor.city %>
    <p>

    <p>
      <strong>Zip:</strong>
      <%= @distributor.zip %>
    <p>

    <p>
      <strong>Price:</strong>
      <%= number_to_currency(@distributor.price / 100.0) %>
    </p>

    <p>
      <strong>Approved:</strong>
      <% if @distributor.approved %>
        &#x2713;
      <% else %>
        &#x2717; <%= link_to 'Approve', approve_admin_distributor_path(@distributor), class: 'btn btn-sm btn-success' %>
      <% end %>
    <p>

    <p>
      <%= link_to icon_text('Edit', 'glyphicon glyphicon-pencil'), edit_admin_distributor_path(@distributor), class: 'btn btn-sm btn-primary' %>
      <%= link_to icon_text('Past Orders', 'glyphicon glyphicon-time'), admin_distributor_orders_path(@distributor), class: 'btn btn-sm btn-primary' %>
      <%= link_to icon_text('New Order', 'glyphicon glyphicon-credit-card'), new_admin_distributor_order_path(@distributor), class: 'btn btn-sm btn-success' %>
    </p>
  </div>
</div>